{{- if .Values.redis.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.redis.labels" . | nindent 4 }}
  {{- with .Values.redis.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.redis.pdb.minAvailable }}
  minAvailable: {{ .Values.redis.pdb.minAvailable }}
  {{- else if .Values.redis.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.redis.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "redis-sentinel.redis.selectorLabels" . | nindent 6 }}
{{- end }}