{{- /*
Secret will only be created if existingSecret is NOT provided
If existingSecret is provided, we assume the secret already exists in the cluster
*/}}
{{- if not .Values.redis.password.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.redis.passwordSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "redis-sentinel.redis.passwordKey" . }}: {{ .Values.redis.password.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}