{{- if .Values.sentinel.enabled }}
{{- $fullname := include "redis-sentinel.fullname" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullname }}-sentinel
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redis-sentinel.sentinel.labels" . | nindent 4 }}
spec:
  serviceName: {{ $fullname }}-sentinel
  replicas: {{ .Values.sentinel.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-sentinel.sentinel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis-sentinel.sentinel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - "redis-sentinel"
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                  - "sentinel"
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: config
          image: {{ include "redis-sentinel.sentinel.image" . }}
          imagePullPolicy: {{ .Values.sentinel.image.pullPolicy }}
          env:
            - name: REDIS_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullname }}-config
                  key: REDIS_NODES
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis-sentinel.redis.passwordSecret" . }}
                  key: {{ include "redis-sentinel.redis.passwordKey" . }}
          command: ["sh", "-c", "/scripts/sentinel_init.sh"]
          volumeMounts:
            - name: sentinel-config
              mountPath: /etc/redis/
            - name: init-script
              mountPath: /scripts/
      containers:
        - name: sentinel
          image: {{ include "redis-sentinel.sentinel.image" . }}
          imagePullPolicy: {{ .Values.sentinel.image.pullPolicy }}
          command: ["redis-sentinel"]
          args: ["/etc/redis/sentinel.conf"]
          resources:
            {{- toYaml .Values.sentinel.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "redis-cli -a $$REDIS_PASSWORD -p {{ if .Values.sentinel }}{{ if .Values.sentinel.config }}{{ .Values.sentinel.config.port | default 26379 }}{{ else }}26379{{ end }}{{ else }}26379{{ end }} --no-auth-warning shutdown"
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "redis-cli -a $$REDIS_PASSWORD -p {{ if .Values.sentinel }}{{ if .Values.sentinel.config }}{{ .Values.sentinel.config.port | default 26379 }}{{ else }}26379{{ end }}{{ else }}26379{{ end }} --no-auth-warning ping | grep PONG"            
            initialDelaySeconds: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.liveness.initialDelaySeconds | default 10 }}{{ else }}10{{ end }}{{ else }}10{{ end }}
            timeoutSeconds: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.liveness.timeoutSeconds | default 5 }}{{ else }}5{{ end }}{{ else }}5{{ end }}
            periodSeconds: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.liveness.periodSeconds | default 5 }}{{ else }}5{{ end }}{{ else }}5{{ end }}
            failureThreshold: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.liveness.failureThreshold | default 10 }}{{ else }}10{{ end }}{{ else }}10{{ end }}
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "redis-cli -a $$REDIS_PASSWORD -p {{ if .Values.sentinel }}{{ if .Values.sentinel.config }}{{ .Values.sentinel.config.port | default 26379 }}{{ else }}26379{{ end }}{{ else }}26379{{ end }} --no-auth-warning ping | grep PONG"
            initialDelaySeconds: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.readiness.initialDelaySeconds | default 5 }}{{ else }}5{{ end }}{{ else }}5{{ end }}
            timeoutSeconds: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.readiness.timeoutSeconds | default 10 }}{{ else }}10{{ end }}{{ else }}10{{ end }}
            periodSeconds: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.readiness.periodSeconds | default 2 }}{{ else }}2{{ end }}{{ else }}2{{ end }}
            failureThreshold: {{ if .Values.probes }}{{ if .Values.probes.sentinel }}{{ .Values.probes.sentinel.readiness.failureThreshold | default 20 }}{{ else }}20{{ end }}{{ else }}20{{ end }}
            successThreshold: 1
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis-sentinel.redis.passwordSecret" . }}
                  key: {{ include "redis-sentinel.redis.passwordKey" . }}
          ports:
            - containerPort: {{ if .Values.sentinel }}{{ if .Values.sentinel.config }}{{ .Values.sentinel.config.port | default 26379 }}{{ else }}26379{{ end }}{{ else }}26379{{ end }}
              name: sentinel
          volumeMounts:
            - name: sentinel-config
              mountPath: /etc/redis/
            - name: data
              mountPath: /data
      volumes:
        - name: init-script
          configMap:
            name: {{ $fullname }}-scripts
            defaultMode: 0777
            items:
              - key: sentinel_init.sh
                path: sentinel_init.sh
        - name: sentinel-config
          emptyDir: {}
        - name: data
          emptyDir: {}
{{- end }}